import React from 'react';
import { Metadata } from 'next';




interface RootLayoutProps {
  children: React.ReactNode;
}
const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {

  return (
    <div className="w-full h-full flex">
    
     <div className="hidden md:block h-full fixed left-0 top-0 bottom-0">
    

      </div>
      <div className="flex-grow md:ml-64 mt-14">{children}</div>
    </div>
  );
};
export const metadata: Metadata = {
  title: 'Assistant',
  description: 'Generated by create next app',
};
export default RootLayout;
