import React from 'react';
import { Metadata } from 'next';
import SuperAdminNavbar from './components/super_admin_nav';

interface RootLayoutProps {
  children: React.ReactNode;
}
const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <div className="w-full h-full flex">
      <div className="hidden md:block h-full fixed left-0 top-0 bottom-0">
        <SuperAdminNavbar />
      </div>
      <div className="flex-grow md:ml-64 mt-14">{children}</div>
    </div>
  );
};
export const metadata: Metadata = {
  title: 'Super Admin',
  description: 'Generated by create next app',
};
export default RootLayout;
