import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import SuperAdminNavbar from './components/super_admin_nav';

interface RootLayoutProps {
  children: React.ReactNode;
  myHeader?: React.ReactNode; // Make specialChildren optional
}
const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Super Admin',
  description: 'Generated by create next app',
};
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full absolute shadow bg-white p-8"></div>
        <div className="w-full h-full flex">
          <div className="hidden md:block h-full fixed left-0 top-0 bottom-0">
            <SuperAdminNavbar />
          </div>
          <div className="flex-grow md:ml-64 mt-14">{children}</div>
        </div>
      </body>
    </html>
  );
}
